#!/usr/bin/env python3
"""Generate TypeScript type literal unions from the Python module registry.

Run from the project root:
    uv run tools/ontology/generate_types.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from src.domain.viewpoints.viewpoint_style_values import SCALE_ENDPOINT_ORDER, STYLE_TOKEN_COLORS
from src.infrastructure.app_bootstrap import build_module_registry, build_runtime_catalogs

_OUTPUT = Path(__file__).resolve().parents[1] / "gui" / "src" / "domain" / "types.generated.ts"

_HEADER = (
    "// This file is auto-generated by tools/ontology/generate_types.py — do not edit manually.\n"
    "// Regenerate with: uv run tools/ontology/generate_types.py (from project root)\n\n"
)


def _const_record(const_name: str, value_type: str, values: dict[str, str]) -> str:
    """A generated lookup, so a colour or a corner is stated once — in the ontology — and the
    frontend receives it rather than keeping a copy that drifts. Three such copies existed and
    disagreed on every domain."""
    items = "\n  ".join(f'"{key}": "{value}",' for key, value in sorted(values.items()))
    return f"export const {const_name}: Record<string, {value_type}> = {{\n  {items}\n}}\n\n"


def _const_array(const_name: str, type_name: str, values: list[str]) -> str:
    items = ",\n  ".join(f'"{v}"' for v in values)
    return (
        f"export const {const_name} = [\n  {items},\n] as const\n"
        f"export type {type_name} = typeof {const_name}[number]\n\n"
    )


def main(argv: list[str]) -> None:
    """Takes no arguments. It used to ignore them, so `--help` regenerated the file instead of
    describing the command — the same defect `export_doc_diagrams.py` had, on a script that writes."""
    argparse.ArgumentParser(prog="generate_types.py", description=__doc__).parse_args(argv[1:])
    # Emit the complete vocabulary (all modules + diagram types) regardless of which
    # optional runtime capabilities are present, so the generated file is identical on
    # every machine — e.g. with or without the confidential assurance store configured.
    registry = build_module_registry(complete_vocabulary=True)

    entity_types = sorted(registry.all_entity_types().keys())
    connection_types = sorted(registry.all_connection_types().keys())
    domain_names = registry.domain_order() + ["unknown"]
    diagram_types = sorted(registry.all_diagram_types().keys())

    out = _HEADER
    out += _const_array("ENTITY_TYPE_NAMES", "EntityTypeName", entity_types)
    out += _const_array("CONNECTION_TYPE_NAMES", "ConnectionTypeName", connection_types)
    out += _const_array("DOMAIN_NAMES", "DomainName", domain_names)
    out += _const_array("DIAGRAM_TYPE_NAMES", "DiagramTypeName", diagram_types)

    # How elements are drawn, from the ontology that declares it. Generated rather than fetched:
    # the frontend needs a colour before any request completes, and a constant the backend
    # generates is the same arrangement `routeTimeoutPolicy.json` already uses.
    catalogs = build_runtime_catalogs(registry)
    appearance = catalogs.ontology.domain_appearance()
    out += _const_record(
        "DOMAIN_COLORS", "string", {name: values["fill"] for name, values in appearance.items()},
    )
    out += _const_record(
        "DOMAIN_BORDER_COLORS", "string",
        {name: values["border"] for name, values in appearance.items()},
    )
    out += _const_record(
        "DOMAIN_CONTAINER_COLORS", "string",
        {name: values["container"] for name, values in appearance.items()},
    )
    # What each style token is painted as, from the one table that declares it. Generated for the
    # same reason `DOMAIN_COLORS` is: the diagram renderer resolves these server-side now, so a second
    # table in the frontend is two palettes that can disagree — which is the incident `DOMAIN_COLORS`
    # itself records.
    out += _const_record("STYLE_TOKEN_COLORS", "string", dict(STYLE_TOKEN_COLORS))
    # The offer order is a separate declaration because it is a separate fact: the palette is a
    # lookup and a lookup has no order, while the endpoints an author is offered are a sequence whose
    # order groups the pairs. `_const_record` sorts, which is right for a lookup and wrong for this.
    out += _const_array("SCALE_ENDPOINT_ORDER", "ScaleEndpointToken", list(SCALE_ENDPOINT_ORDER))

    out += _const_record(
        "ENTITY_TYPE_CORNERS", "'square' | 'rounded' | 'diagonal'",
        dict(catalogs.ontology.corner_by_entity_type()),
    )

    _OUTPUT.write_text(out, encoding="utf-8")
    print(f"Generated {_OUTPUT}")


if __name__ == "__main__":
    main(sys.argv)
