---
artifact-id: ARC@1777452513.mmuM5i.reverse-architecture-architecture-conformance-review
artifact-type: diagram
name: Reverse Architecture & Architecture Conformance Review
version: 0.1.0
status: draft
keywords:
- workflow
- reverse-architecture
- conformance
- process
diagram-type: archimate-business
entity-ids-used:
- FNC@1777390465.SXt2mM.check-model-coverage
- FNC@1777390462.erPw5B.explore-system-structure
- FNC@1777390456.ns4pWw.extract-architecture-baseline
- FNC@1777390463.oRz6Qe.map-elements-to-architecture-concepts
- FNC@1777390459.omV6nu.report-architecture-deviations
- FNC@1777390458.tFTeOT.assess-implementation-against-model
- PRC@1777293168.CYgU64.reverse-architecture
- PRC@1776635649.vlE-5j.review-architecture-conformance
- SRV@1776694843.GsUtNL.model-authoring-service
- SRV@1712870400.Ij6Kl6.validation-service
- SRV@1712870400.Qr8St8.discovery-querying-stats-service
connection-ids-used:
- SRV@1776694843.GsUtNL---PRC@1777293168.CYgU64@@archimate-serving
- SRV@1712870400.Qr8St8---PRC@1776635649.vlE-5j@@archimate-serving
- FNC@1777390456.ns4pWw---FNC@1777390458.tFTeOT@@archimate-triggering
- FNC@1777390458.tFTeOT---FNC@1777390459.omV6nu@@archimate-triggering
- PRC@1777293168.CYgU64---FNC@1777390465.SXt2mM@@archimate-composition
- PRC@1777293168.CYgU64---FNC@1777390462.erPw5B@@archimate-composition
- PRC@1777293168.CYgU64---FNC@1777390463.oRz6Qe@@archimate-composition
- PRC@1776635649.vlE-5j---FNC@1777390456.ns4pWw@@archimate-composition
- PRC@1776635649.vlE-5j---FNC@1777390459.omV6nu@@archimate-composition
- PRC@1776635649.vlE-5j---FNC@1777390458.tFTeOT@@archimate-composition
last-updated: '2026-08-13T13:58:25Z'
---
@startuml reverse-architecture---architecture-conformance-review
hide stereotype

skinparam defaultFontName SansSerif
skinparam defaultFontSize 12
skinparam shadowing false
skinparam roundcorner 4
skinparam backgroundColor #FAFAFA

skinparam linetype ortho
skinparam nodesep 60
skinparam ranksep 80
!define Rel_Access(from, to, label) from -[dotted]-> to
!define Rel_Access_Up(from, to, label) from -[dotted]up-> to
!define Rel_Access_Down(from, to, label) from -[dotted]down-> to
!define Rel_Access_Left(from, to, label) from -[dotted]left-> to
!define Rel_Access_Right(from, to, label) from -[dotted]right-> to
!define Rel_Aggregation(from, to, label) from o-- to
!define Rel_Aggregation_Up(from, to, label) from o-up- to
!define Rel_Aggregation_Down(from, to, label) from o-down- to
!define Rel_Aggregation_Left(from, to, label) from o-left- to
!define Rel_Aggregation_Right(from, to, label) from o-right- to
!define Rel_Assignment(from, to, label) from --> to
!define Rel_Assignment_Up(from, to, label) from -up-> to
!define Rel_Assignment_Down(from, to, label) from -down-> to
!define Rel_Assignment_Left(from, to, label) from -left-> to
!define Rel_Assignment_Right(from, to, label) from -right-> to
!define Rel_Association(from, to, label) from -- to
!define Rel_Association_Up(from, to, label) from -up- to
!define Rel_Association_Down(from, to, label) from -down- to
!define Rel_Association_Left(from, to, label) from -left- to
!define Rel_Association_Right(from, to, label) from -right- to
!define Rel_Composition(from, to, label) from *-- to
!define Rel_Composition_Up(from, to, label) from *-up- to
!define Rel_Composition_Down(from, to, label) from *-down- to
!define Rel_Composition_Left(from, to, label) from *-left- to
!define Rel_Composition_Right(from, to, label) from *-right- to
!define Rel_Flow(from, to, label) from ..> to
!define Rel_Flow_Up(from, to, label) from .up.> to
!define Rel_Flow_Down(from, to, label) from .down.> to
!define Rel_Flow_Left(from, to, label) from .left.> to
!define Rel_Flow_Right(from, to, label) from .right.> to
!define Rel_Influence(from, to, label) from ..> to
!define Rel_Influence_Up(from, to, label) from .up.> to
!define Rel_Influence_Down(from, to, label) from .down.> to
!define Rel_Influence_Left(from, to, label) from .left.> to
!define Rel_Influence_Right(from, to, label) from .right.> to
!define Rel_Realization(from, to, label) from ..|> to
!define Rel_Realization_Up(from, to, label) from .up.|> to
!define Rel_Realization_Down(from, to, label) from .down.|> to
!define Rel_Realization_Left(from, to, label) from .left.|> to
!define Rel_Realization_Right(from, to, label) from .right.|> to
!define Rel_Serving(from, to, label) from --> to
!define Rel_Serving_Up(from, to, label) from -up-> to
!define Rel_Serving_Down(from, to, label) from -down-> to
!define Rel_Serving_Left(from, to, label) from -left-> to
!define Rel_Serving_Right(from, to, label) from -right-> to
!define Rel_Specialization(from, to, label) from --|> to
!define Rel_Specialization_Up(from, to, label) from -up-|> to
!define Rel_Specialization_Down(from, to, label) from -down-|> to
!define Rel_Specialization_Left(from, to, label) from -left-|> to
!define Rel_Specialization_Right(from, to, label) from -right-|> to
!define Rel_Triggering(from, to, label) from --> to
!define Rel_Triggering_Up(from, to, label) from -up-> to
!define Rel_Triggering_Down(from, to, label) from -down-> to
!define Rel_Triggering_Left(from, to, label) from -left-> to
!define Rel_Triggering_Right(from, to, label) from -right-> to
skinparam rectangle<<CommonGrouping>> {
  BackgroundColor #F3F1EB
  BorderColor #45433F
}
skinparam rectangle<<function>> {
  BackgroundColor #E5DFD3
  BorderColor #45433F
  RoundCorner 14
}
skinparam rectangle<<process>> {
  BackgroundColor #E5DFD3
  BorderColor #45433F
  RoundCorner 14
}
skinparam rectangle<<service>> {
  BackgroundColor #E5DFD3
  BorderColor #45433F
  RoundCorner 14
}
sprite $archimate_function <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M2.9 11.7V5.4L8 3.1l5.1 2.3v6.3L8 9.2z"  fill="#252327" stroke="none"/></svg>
sprite $archimate_process <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M2.6 4.1h6.3V2.8l4.5 5.2-4.5 5.2v-1.3H2.6z"  fill="#252327" stroke="none"/></svg>
sprite $archimate_service <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M3.2 4.1h7.2a2.8 2.8 0 0 1 0 7.8H3.2a2.8 2.8 0 0 1 0-7.8z"  fill="#252327" stroke="none"/></svg>
skinparam wrapWidth 240
top to bottom direction

skinparam maxMessageSize 240

title Reverse Architecture & Architecture Conformance Review

rectangle "Services" <<CommonGrouping>> as GRPT_1 {
  rectangle "<$archimate_service{scale=1.2}> Model Authoring Service\n«Application Service»" <<service>> as SRV_GsUtNL
  rectangle "<$archimate_service{scale=1.2}> Discovery, Querying & Stats Service\n«Application Service»" <<service>> as SRV_Qr8St8
}
SRV_GsUtNL -[hidden]right- SRV_Qr8St8

rectangle "Processes" <<CommonGrouping>> as GRPT_2 {
  rectangle "<$archimate_process{scale=1.2}> Reverse Architecture\n«Business Process»" <<process>> as PRC_CYgU64 {
    rectangle "<$archimate_function{scale=1.2}> Check Model Coverage\n«Application Function»" <<function>> as FNC_SXt2mM
    rectangle "<$archimate_function{scale=1.2}> Explore System Structure\n«Application Function»" <<function>> as FNC_erPw5B
    rectangle "<$archimate_function{scale=1.2}> Map Elements to Architecture Concepts\n«Business Function»" <<function>> as FNC_oRz6Qe
    FNC_SXt2mM -[hidden]down- FNC_erPw5B
    FNC_erPw5B -[hidden]down- FNC_oRz6Qe
  }
  rectangle "<$archimate_process{scale=1.2}> Architecture Conformance Review\n«Business Process»" <<process>> as PRC_vlE_5j {
    rectangle "<$archimate_function{scale=1.2}> Extract Architecture Baseline\n«Application Function»" <<function>> as FNC_ns4pWw
    rectangle "<$archimate_function{scale=1.2}> Report Architecture Deviations\n«Application Function»" <<function>> as FNC_omV6nu
    rectangle "<$archimate_function{scale=1.2}> Assess Implementation Against Model\n«Business Function»" <<function>> as FNC_tFTeOT
    FNC_ns4pWw -[hidden]down- FNC_tFTeOT
    FNC_tFTeOT -[hidden]down- FNC_omV6nu
  }
}
PRC_CYgU64 -[hidden]right- PRC_vlE_5j

rectangle "<$archimate_service{scale=1.2}> Verification Service\n«Application Service»" <<service>> as SRV_Ij6Kl6
GRPT_2 -[hidden]down- SRV_Ij6Kl6

' Connections
SRV_GsUtNL -down-> PRC_CYgU64
SRV_Qr8St8 -down-> PRC_vlE_5j
FNC_ns4pWw --> FNC_tFTeOT
FNC_tFTeOT --> FNC_omV6nu

@enduml
