---
artifact-id: ARC@1784484008.jKQxr7.value-stream-assure-a-system-release
artifact-type: diagram
name: 'Value Stream: Assure a System Release'
version: 0.1.0
status: active
diagram-type: archimate-layered
viewpoint:
  slug: value-stream
  version: 2
entity-ids-used:
- CAP@1784482442.0kQIHh.architecture-analysis-visualization
- CAP@1784482433.Eb_x83.integrated-safety-security-compliance-assurance
- CAP@1784482403.pLMHKe.architecture-knowledge-management
- STK@1780655839.AsnqRa.risk-compliance-officer
- STK@1780655839.r4P3gy.safety-security-analyst
- VAL@1784482970.F6BTAd.provable-assurance-without-specialist-overhead
- VS@1784483047.LkIafZ.treat-risks-track-compliance-obligations
- VS@1784483045.R-f15Z.contextualize-supply-chain-risk
- VS@1784483036.S4ZTiY.analyze-hazards-threats
- VS@1784483034.eqoIe2.establish-the-assurance-analysis-context
- VS@1784482992.fK25Bo.assure-a-system-release
- VS@1784483059.hRUzQe.build-seal-the-assurance-case
connection-ids-used:
- CAP@1784482403.pLMHKe---VS@1784483034.eqoIe2@@archimate-serving
- CAP@1784482433.Eb_x83---VS@1784482992.fK25Bo@@archimate-serving
- CAP@1784482433.Eb_x83---VS@1784483034.eqoIe2@@archimate-serving
- CAP@1784482433.Eb_x83---VS@1784483036.S4ZTiY@@archimate-serving
- CAP@1784482433.Eb_x83---VS@1784483045.R-f15Z@@archimate-serving
- CAP@1784482433.Eb_x83---VS@1784483047.LkIafZ@@archimate-serving
- CAP@1784482433.Eb_x83---VS@1784483059.hRUzQe@@archimate-serving
- CAP@1784482442.0kQIHh---VS@1784483059.hRUzQe@@archimate-serving
- STK@1780655839.AsnqRa---VS@1784482992.fK25Bo@@archimate-association
- VAL@1784482970.F6BTAd---STK@1780655839.AsnqRa@@archimate-association
- STK@1780655839.r4P3gy---VS@1784482992.fK25Bo@@archimate-association
- VAL@1784482970.F6BTAd---STK@1780655839.r4P3gy@@archimate-association
- VS@1784482992.fK25Bo---VAL@1784482970.F6BTAd@@archimate-association
- VS@1784483034.eqoIe2---VS@1784483036.S4ZTiY@@archimate-flow
- VS@1784483036.S4ZTiY---VS@1784483045.R-f15Z@@archimate-flow
- VS@1784483045.R-f15Z---VS@1784483047.LkIafZ@@archimate-flow
- VS@1784483047.LkIafZ---VS@1784483059.hRUzQe@@archimate-flow
- VS@1784482992.fK25Bo---VS@1784483047.LkIafZ@@archimate-composition
- VS@1784482992.fK25Bo---VS@1784483045.R-f15Z@@archimate-composition
- VS@1784482992.fK25Bo---VS@1784483036.S4ZTiY@@archimate-composition
- VS@1784482992.fK25Bo---VS@1784483034.eqoIe2@@archimate-composition
- VS@1784482992.fK25Bo---VS@1784483059.hRUzQe@@archimate-composition
last-updated: '2026-08-13T13:59:03Z'
---
@startuml value-stream--assure-a-system-release
hide stereotype

skinparam defaultFontName SansSerif
skinparam defaultFontSize 12
skinparam shadowing false
skinparam roundcorner 4
skinparam backgroundColor #FAFAFA

skinparam linetype ortho
skinparam nodesep 60
skinparam ranksep 80
!define Rel_Access(from, to, label) from -[dotted]-> to
!define Rel_Access_Up(from, to, label) from -[dotted]up-> to
!define Rel_Access_Down(from, to, label) from -[dotted]down-> to
!define Rel_Access_Left(from, to, label) from -[dotted]left-> to
!define Rel_Access_Right(from, to, label) from -[dotted]right-> to
!define Rel_Aggregation(from, to, label) from o-- to
!define Rel_Aggregation_Up(from, to, label) from o-up- to
!define Rel_Aggregation_Down(from, to, label) from o-down- to
!define Rel_Aggregation_Left(from, to, label) from o-left- to
!define Rel_Aggregation_Right(from, to, label) from o-right- to
!define Rel_Assignment(from, to, label) from --> to
!define Rel_Assignment_Up(from, to, label) from -up-> to
!define Rel_Assignment_Down(from, to, label) from -down-> to
!define Rel_Assignment_Left(from, to, label) from -left-> to
!define Rel_Assignment_Right(from, to, label) from -right-> to
!define Rel_Association(from, to, label) from -- to
!define Rel_Association_Up(from, to, label) from -up- to
!define Rel_Association_Down(from, to, label) from -down- to
!define Rel_Association_Left(from, to, label) from -left- to
!define Rel_Association_Right(from, to, label) from -right- to
!define Rel_Composition(from, to, label) from *-- to
!define Rel_Composition_Up(from, to, label) from *-up- to
!define Rel_Composition_Down(from, to, label) from *-down- to
!define Rel_Composition_Left(from, to, label) from *-left- to
!define Rel_Composition_Right(from, to, label) from *-right- to
!define Rel_Flow(from, to, label) from ..> to
!define Rel_Flow_Up(from, to, label) from .up.> to
!define Rel_Flow_Down(from, to, label) from .down.> to
!define Rel_Flow_Left(from, to, label) from .left.> to
!define Rel_Flow_Right(from, to, label) from .right.> to
!define Rel_Influence(from, to, label) from ..> to
!define Rel_Influence_Up(from, to, label) from .up.> to
!define Rel_Influence_Down(from, to, label) from .down.> to
!define Rel_Influence_Left(from, to, label) from .left.> to
!define Rel_Influence_Right(from, to, label) from .right.> to
!define Rel_Realization(from, to, label) from ..|> to
!define Rel_Realization_Up(from, to, label) from .up.|> to
!define Rel_Realization_Down(from, to, label) from .down.|> to
!define Rel_Realization_Left(from, to, label) from .left.|> to
!define Rel_Realization_Right(from, to, label) from .right.|> to
!define Rel_Serving(from, to, label) from --> to
!define Rel_Serving_Up(from, to, label) from -up-> to
!define Rel_Serving_Down(from, to, label) from -down-> to
!define Rel_Serving_Left(from, to, label) from -left-> to
!define Rel_Serving_Right(from, to, label) from -right-> to
!define Rel_Specialization(from, to, label) from --|> to
!define Rel_Specialization_Up(from, to, label) from -up-|> to
!define Rel_Specialization_Down(from, to, label) from -down-|> to
!define Rel_Specialization_Left(from, to, label) from -left-|> to
!define Rel_Specialization_Right(from, to, label) from -right-|> to
!define Rel_Triggering(from, to, label) from --> to
!define Rel_Triggering_Up(from, to, label) from -up-> to
!define Rel_Triggering_Down(from, to, label) from -down-> to
!define Rel_Triggering_Left(from, to, label) from -left-> to
!define Rel_Triggering_Right(from, to, label) from -right-> to
skinparam rectangle<<MotivationGrouping>> {
  BackgroundColor #EAE0EF
  BorderColor #3F3842
}
skinparam rectangle<<StrategyGrouping>> {
  BackgroundColor #F8E1B6
  BorderColor #48391C
}
skinparam rectangle<<capability>> {
  BackgroundColor #EFBD5D
  BorderColor #48391C
  RoundCorner 14
}
skinparam rectangle<<stakeholder>> {
  BackgroundColor #D1BADC
  BorderColor #3F3842
  DiagonalCorner 10
}
skinparam rectangle<<value>> {
  BackgroundColor #D1BADC
  BorderColor #3F3842
  DiagonalCorner 10
}
skinparam rectangle<<value_stream>> {
  BackgroundColor #EFBD5D
  BorderColor #48391C
  RoundCorner 14
}
sprite $archimate_capability <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M3.10 11.25h9.80v1.30H3.10z" fill="#252327"/><path d="M4.00 8.80h1.90v3.10H4.00z" fill="#252327"/><path d="M6.80 6.80h1.90v5.10H6.80z" fill="#252327"/><path d="M9.60 4.70h1.90v7.20H9.60z" fill="#252327"/></svg>
sprite $archimate_stakeholder <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M3.1 4.1h7.3L13 8l-2.6 3.9H3.1L5.6 8z"  fill="#252327" stroke="none"/></svg>
sprite $archimate_value <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><ellipse cx="8" cy="8" rx="6.5" ry="4"  fill="none" stroke="#252327" stroke-width="1.3"/></svg>
sprite $archimate_value_stream <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M2.5 5h7l2.5 3-2.5 3h-7l2-3z"  fill="#252327" stroke="none"/></svg>
skinparam wrapWidth 240
skinparam maxMessageSize 240

title Value Stream: Assure a System Release

rectangle "Motivation" <<MotivationGrouping>> as DOM_motivation {
  rectangle "<$archimate_value{scale=1.2}> Provable Assurance Without Specialist Overhead" <<value>> as VAL_F6BTAd

  rectangle "Stakeholders" <<MotivationGrouping>> as GRPT_motivation_1 {
    rectangle "<$archimate_stakeholder{scale=1.2}> Risk & Compliance Officer" <<stakeholder>> as STK_AsnqRa
    rectangle "<$archimate_stakeholder{scale=1.2}> Safety / Security Analyst" <<stakeholder>> as STK_r4P3gy
  }
  STK_AsnqRa -[hidden]right- STK_r4P3gy

}

rectangle "Strategy" <<StrategyGrouping>> as DOM_strategy {
  rectangle "Capabilities" <<StrategyGrouping>> as GRPT_strategy_1 {
    rectangle "<$archimate_capability{scale=1.2}> Architecture Analysis & Visualization" <<capability>> as CAP_0kQIHh
    rectangle "<$archimate_capability{scale=1.2}> Integrated Safety, Security & Compliance Assurance" <<capability>> as CAP_Eb_x83
    rectangle "<$archimate_capability{scale=1.2}> Architecture Knowledge Management" <<capability>> as CAP_pLMHKe
  }
  CAP_0kQIHh -[hidden]right- CAP_Eb_x83
  CAP_Eb_x83 -[hidden]right- CAP_pLMHKe

  rectangle "<$archimate_value_stream{scale=1.2}> Assure a System Release" <<value_stream>> as VS_fK25Bo {
    rectangle "<$archimate_value_stream{scale=1.2}> Treat Risks & Track Compliance Obligations" <<value_stream>> as VS_LkIafZ
    rectangle "<$archimate_value_stream{scale=1.2}> Contextualize Supply-Chain Risk" <<value_stream>> as VS_R_f15Z
    rectangle "<$archimate_value_stream{scale=1.2}> Analyze Hazards & Threats" <<value_stream>> as VS_S4ZTiY
    rectangle "<$archimate_value_stream{scale=1.2}> Establish the Assurance Analysis Context" <<value_stream>> as VS_eqoIe2
    rectangle "<$archimate_value_stream{scale=1.2}> Build & Seal the Assurance Case" <<value_stream>> as VS_hRUzQe
    VS_eqoIe2 -[hidden]down- VS_S4ZTiY
    VS_S4ZTiY -[hidden]down- VS_R_f15Z
    VS_R_f15Z -[hidden]down- VS_LkIafZ
    VS_LkIafZ -[hidden]down- VS_hRUzQe
  }

}

' Connections
CAP_pLMHKe --> VS_eqoIe2
CAP_Eb_x83 -down-> VS_fK25Bo
CAP_Eb_x83 --> VS_eqoIe2
CAP_Eb_x83 --> VS_S4ZTiY
CAP_Eb_x83 --> VS_R_f15Z
CAP_Eb_x83 --> VS_LkIafZ
CAP_Eb_x83 --> VS_hRUzQe
CAP_0kQIHh --> VS_hRUzQe
STK_AsnqRa -down- VS_fK25Bo
VAL_F6BTAd -down- STK_AsnqRa
STK_r4P3gy -down- VS_fK25Bo
VAL_F6BTAd -down- STK_r4P3gy
VS_fK25Bo -up- VAL_F6BTAd
VS_eqoIe2 ..> VS_S4ZTiY
VS_S4ZTiY ..> VS_R_f15Z
VS_R_f15Z ..> VS_LkIafZ
VS_LkIafZ ..> VS_hRUzQe

@enduml
