"""Operations whose response contract the manifest declares but the surface does not yet meet.

The manifest names a DTO for every operation. Most operations still answer with an open object —
a model with ``extra="allow"``, which documents "an object" and promises nothing about its
contents — or with an inline schema, or with ``application/json`` where the contract says media.
This is the list of those, and it is the measure of the response-contract work remaining.

It shrinks per router as Phase 1 authors each surface's DTOs, and it is **empty** when the
contract is complete. Nothing may be added: a new operation declares its DTO when it is written,
which is cheap then and expensive later.
"""

from __future__ import annotations

#: Operation ids whose declared success body is not yet the DTO the manifest names.
UNTYPED_RESPONSE_OPERATIONS: frozenset[str] = frozenset({
    "admin_create_connection",
    "admin_create_diagram",
    "admin_create_entity",
    "admin_delete_connection",
    "admin_delete_diagram",
    "admin_delete_entity",
    "admin_read_server_info",
    "admin_update_entity",
    "assurance_create_analysis",
    "assurance_create_analysis_node",
    "assurance_create_edge",
    "assurance_create_group",
    "assurance_delete_analysis",
    "assurance_delete_edge",
    "assurance_delete_group",
    "assurance_delete_node",
    "assurance_export_aibom",
    "assurance_file_analysis",
    "assurance_list_aibom_roles",
    "assurance_list_analyses",
    "assurance_list_baselines",
    "assurance_list_diagrams",
    "assurance_list_edges",
    "assurance_list_groups",
    "assurance_list_nodes",
    "assurance_list_participating_nodes",
    "assurance_model_this",
    "assurance_read_aibom_coverage",
    "assurance_read_analysis",
    "assurance_read_analysis_completeness",
    "assurance_read_analysis_matrix",
    "assurance_read_coverage",
    "assurance_read_edge_catalog",
    "assurance_read_gsn_draft",
    "assurance_read_gsn_render",
    "assurance_read_guidance",
    "assurance_read_node",
    "assurance_read_node_neighbors",
    "assurance_read_risk_register",
    "assurance_read_stats",
    "assurance_read_store_status",
    "assurance_record_factor_assessment",
    "assurance_record_gsn_publication",
    "assurance_register_arch_ref",
    "assurance_reload_store",
    "assurance_render_analysis_diagram",
    "assurance_scan_aibom_candidates",
    "assurance_seal_baseline",
    "assurance_search_nodes",
    "assurance_update_analysis",
    "assurance_update_node",
    "assurance_verify_store",
    "connections_read_entity_neighbors",
    "connections_read_ontology",
    "connections_read_relation_notations",
    "diagrams_create_diagram",
    "diagrams_delete_diagram",
    "diagrams_discover_diagram_entities",
    "diagrams_download_diagram_source",
    "diagrams_list_datatype_type_usages",
    "diagrams_list_datatype_types",
    "diagrams_list_diagram_types",
    "diagrams_list_diagrams",
    "diagrams_preview_diagram",
    "diagrams_read_diagram",
    "diagrams_read_diagram_context",
    "diagrams_read_diagram_image",
    "diagrams_read_diagram_svg",
    "diagrams_read_diagram_type_ui_config",
    "diagrams_replace_diagram",
    "diagrams_search_entity_display_items",
    "diagrams_set_diagram_edge_label",
    "diagrams_sync_diagram_to_model",
    "documents_create_document",
    "documents_list_document_types",
    "documents_read_document_schemata",
    "documents_search_reference_artifacts",
    "documents_update_document",
    "entities_allocate_identifiers",
    "entities_search_artifacts",
    "entities_search_display_artifacts",
    "events_stream_events",
    "groups_archive_group",
    "groups_create_group",
    "groups_delete_group",
    "groups_list_groups",
    "groups_rename_group",
    "groups_unarchive_group",
    "groups_update_group",
    "matrices_create_matrix",
    "matrices_preview_matrix",
    "matrices_read_matrix_config",
    "matrices_replace_matrix",
    "promotion_execute_promotion",
    "promotion_plan_promotion",
    "sync_read_sync_changes",
    "sync_read_sync_status",
    "sync_save_engagement",
    "sync_save_enterprise",
    "sync_submit_enterprise",
    "sync_withdraw_enterprise",
    "taxonomy_list_modules",
    "taxonomy_read_authoring_guidance",
    "taxonomy_read_backend_identity",
    "taxonomy_read_entity_taxonomy",
    "taxonomy_read_repository_stats",
    "taxonomy_read_write_help",
    "viewpoints_execute_viewpoint",
    "viewpoints_execute_viewpoint_diagram",
    "viewpoints_execute_viewpoint_projection",
    "viewpoints_export_viewpoint_csv",
    "viewpoints_export_viewpoint_render",
    "viewpoints_list_viewpoint_referencers",
    "viewpoints_list_viewpoints",
    "viewpoints_read_criteria_catalog",
    "viewpoints_read_diagram_viewpoint_projection",
    "viewpoints_read_viewpoint_pins",
    "viewpoints_replace_viewpoint_pins",
    "viewpoints_summarize_viewpoint",
})
