"""Apply the versioned security-signals migrations to a live connection.

One explicit version table (``signals_schema_meta``), one ordered migration
list (``src.domain.assurance.signals_schema``), one transaction per migration. The
signal-snapshot aggregate is the sole signals model.

A store written before the snapshot rename is stamped at the version that introduced
the snapshot tables but carries the old table names, so the migration loop correctly
skips that version and every subsequent query then fails with an opaque ``no such
table``. That case is detected here and raised as a typed, actionable error instead —
the runtime counterpart of the upgrade step's ``signals-schema-pre-rename`` finding.
"""

from __future__ import annotations

from typing import Any

from src.domain.assurance.signals_schema import (
    SIGNALS_MIGRATIONS,
    SIGNALS_SCHEMA_VERSION,
    SNAPSHOT_TABLES_VERSION,
    signals_migration_statements,
)

_BASELINE_VERSION = 1
_PRE_RENAME_TABLE = "security_refresh_runs"
_CURRENT_TABLE = "security_signal_snapshots"

#: The pre-rename SIGNAL tables, in FK-safe drop order (children before parents).
#: Everything they hold is regenerated by re-running ingest against the SBOM and
#: advisory sources. Deliberately scoped to signals: in the co-located backend the
#: same database also holds the authored STPA/CAST/GRC model, which is NOT
#: regenerable and must never be caught by a signals repair.
PRE_RENAME_TABLES: tuple[str, ...] = (
    "run_vulnerability_findings",
    "run_components",
    "security_refresh_runs",
)

__all__ = [
    "PRE_RENAME_TABLES",
    "SIGNALS_MIGRATIONS",
    "SIGNALS_SCHEMA_VERSION",
    "SignalsSchemaUnsupportedError",
    "apply_signals_migrations",
    "signals_schema_version",
]


class SignalsSchemaUnsupportedError(RuntimeError):
    """The signals store predates the snapshot rename and has no upgrade path."""


def _is_pre_rename(conn: Any) -> bool:
    """One sqlite_master lookup for both table names. Only consulted when the
    migration loop is about to skip everything, so a current store pays a single
    cheap query per connection open and never the full table scan."""
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name IN (?, ?)",
        (_CURRENT_TABLE, _PRE_RENAME_TABLE),
    ).fetchall()
    names = {row["name"] if hasattr(row, "keys") else row[0] for row in rows}
    return _PRE_RENAME_TABLE in names and _CURRENT_TABLE not in names


def signals_schema_version(conn: Any) -> int:
    conn.execute(
        "CREATE TABLE IF NOT EXISTS signals_schema_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)"
    )
    row = conn.execute(
        "SELECT value FROM signals_schema_meta WHERE key = 'schema_version'"
    ).fetchone()
    if row is None:
        return _BASELINE_VERSION
    return int(row["value"] if isinstance(row, dict) or hasattr(row, "keys") else row[0])


def apply_signals_migrations(conn: Any) -> int:
    """Bring the signals schema to the current version; one transaction per
    migration (SQLite DDL is transactional). Returns the resulting version.

    Safe to call concurrently from several connections, which the threadpool does on every
    connection it opens. The stamped version is re-read inside each migration's write
    transaction, because reading it beforehand only says what was true before this connection
    waited for the write lock. A migration must not rely on its own statements being
    individually idempotent: creating a table can be written ``IF NOT EXISTS``, renaming a
    column cannot, and the second connection to run one would fail on the already-renamed
    schema.
    """
    current = signals_schema_version(conn)
    if current >= SNAPSHOT_TABLES_VERSION and _is_pre_rename(conn):
        raise SignalsSchemaUnsupportedError(
            "This security-signals schema predates the signal-snapshot rename: it is "
            f"stamped version {current} but still carries the {_PRE_RENAME_TABLE} tables. "
            "Version 2's DDL was renamed in place during pre-alpha, so no upgrade path "
            "exists. Repair: drop the pre-rename SIGNAL tables "
            f"({', '.join(PRE_RENAME_TABLES)}), reset signals_schema_meta.schema_version to "
            f"{_BASELINE_VERSION} so the current DDL is reapplied, then re-run ingest — the "
            "dropped contents are regenerated from the SBOM/advisory sources. Resetting the "
            "stamp is REQUIRED: dropping the tables alone leaves the schema stamped current "
            "with no signal tables at all, which fails exactly the same way. Do NOT delete "
            "the assurance database file: in the co-located backend it also holds the "
            "STPA/CAST/GRC model, which is authored content and is NOT regenerable."
        )
    for version, ddl in SIGNALS_MIGRATIONS:
        if version <= current:
            continue
        try:
            conn.execute("BEGIN IMMEDIATE")
        except Exception:  # noqa: BLE001 — already inside an implicit transaction
            pass
        try:
            if signals_schema_version(conn) >= version:
                # Another connection applied this migration while this one waited for the
                # write lock. Its statements have already run; re-running them is not safe.
                conn.commit()
                current = version
                continue
            for statement in signals_migration_statements(ddl):
                conn.execute(statement)
            conn.execute(
                "INSERT OR REPLACE INTO signals_schema_meta(key, value) VALUES ('schema_version', ?)",
                (str(version),),
            )
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        current = version
    return current
